version: '3'
services:
  dbt-bq-dtc:
    build:
      context: .
      target: dbt-bigquery
    image: dbt/bigquery
    volumes:
      - ~/Github/Data-Engineer/course-data-engineering-zoomcamp/week_4/taxi-rides-ny-project:/usr/app
      - ~/.dbt/:/root/.dbt/
      - ~/Github/Data-Engineer/course-data-engineering-zoomcamp/keys/dbt-agent-sa.json:/.google/credentials/dbt-agent-sa.json
    network_mode: host