version: '2'

services:
  spark:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    ports:
      - '8080:8080'
      - '8081:8081'
      - '8888:8888' # this port is for jupyter notebook
      - '4040:4040' # this port is for spark UI, you may need to open 4041 or 4042 in case 4040 is occupied  
    volumes:
      - "./data:${HOME}/spark/data:rw"
      - "./code:${HOME}/spark/code:rw"
    tty: true